[project]
name = "drug-manuscript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars>=1.21.0",
    "tqdm>=4.67.1",
]

[tool.ruff]
line-length = 120
